services:
  db:
    image: postgres:latest
    container_name: wasserwaage-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

  postgrest:
    image: postgrest/postgrest:latest
    container_name: wasserwaage-api
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PGRST_DB_SCHEMA: ${POSTGRES_DB_SCHEMA}
      PGRST_DB_ANON_ROLE: ${POSTGRES_ANON_ROLE}
      PGRST_JWT_SECRET: ${POSTGRES_JWT_SECRET}

    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
