create schema api;

create table api.tilt_angles (
    id int primary key generated by default as identity,
    x float not null,
    y float not null,
    z float not null,
    created_at timestamp not null default now()
);

create role web_anon nologin;
grant usage on schema api to web_anon;
grant select on api.tilt_angles to web_anon;
grant web_anon to authenticator;

create role web_user nologin;
grant usage on schema api to web_user;
grant select, insert, delete on api.tilt_angles to web_user;
grant web_user to authenticator;
